### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by carolstran**
:wave:! GitHub Classroom created this pull request as a place for your teacher to leave feedback on your work. It will update automatically. **Don’t close or merge this pull request**, unless you’re instructed to do so by your teacher.

In this pull request, your teacher can leave comments and feedback on your code. Click the **Subscribe** button to be notified if that happens.

Click the **Files changed** or **Commits** tab to see all of the changes pushed to `main` since the assignment started. Your teacher can see this too.

<details>
<summary>
<strong>Notes for teachers</strong>
</summary>

Use this PR to leave feedback. Here are some tips:

- Click the **Files changed** tab to see all of the changes pushed to `main` since the assignment started. To leave comments on specific lines of code, put your cursor over a line of code and click the blue **+** (plus sign). To learn more about comments, read “[Commenting on a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request)”.
- Click the **Commits** tab to see the commits pushed to `main`. Click a commit to see specific changes.
- If you turned on autograding, then click the **Checks** tab to see the results.
- This page is an overview. It shows commits, line comments, and general comments. You can leave a general comment below.

For more information about this pull request, read “[Leaving assignment feedback in GitHub](https://classroom.github.com/help/leaving-feedback-in-github)”.
</details>

Subscribed: @monica-pons

### CODE REVIEW

**Comment by carolstran** [comment]
👋🏼  @monica-pons, are you still working on this? If yes then I can wait to give feedback until after you're done, just let me know 😊

**Comment by monica-pons** [comment]
Hi Carolyn,

Thanks for your message!

Yes, I am still working on it, but I will only be able to finish it next
week, is that ok?

Are you the teacher for today's session as well?

Cheers,

Monica

--
Monica Pons
monica.pons@gmail.com

**Comment by carolstran** [comment]
@monica-pons Totally fine, no stress! I just didn't want to review it now and then repeat things you're already working it 😊 

I'm not teaching tonight, but @typeoh is 🎉

**Comment by monica-pons** [comment]
Hi Carolyn,

I just wanted to say sorry I haven't been able to finish the homework yet.

I've been very busy studying for a final exam at Uni, and will complete the
exercise as soon as I can.

Thank you,

Monica

--
Monica Pons
monica.pons@gmail.com

**Comment by carolstran** [comment]
Hey @monica-pons 👋🏼  Honestly I'm not stressed about it and you shouldn't be either 😊  There's so much going on right now and one homework assignment isn't a big deal. As long as you feel like you're keeping up with the course material, that's the most important thing (in the context of this React course, not life lol). 

If you ever do get around to it and want feedback, just ping me. I'm available 💖

**Pull request closed without merging**
